import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../styles/index.css';

interface IProps {
    children: React.ReactNode;
}

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Майстерня рукожопов',
    description: 'Generated by create next app',
};

export default function Layout({ children }: IProps) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div id={'root'}>{children}</div>
                <div id={'root-modal'}></div>
            </body>
        </html>
    );
}
